apiVersion: apps/v1
kind: Deployment
metadata:
  name: time-app
  namespace: time-app
  labels:
    app: time-app
spec:
  replicas: 1
  template:
    metadata:
      name: time-app
      labels:
        app: time-app
    spec:
      containers:
        - name: time-app
          image: lnanjangud653/time-app:2.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
          env:
            - name: "REDIS_URL"
              value: "172.16.48.34:6379"
            - name: "REDIS_PASSWORD"
              value: "VMware1!"
      restartPolicy: Always
  selector:
    matchLabels:
      app: time-app
---
apiVersion: v1
kind: Service
metadata:
  name: time-app
spec:
  selector:
    app: time-app
  ports:
    - name: app-service-port
      port: 8888
      protocol: TCP
      targetPort: 8888
  type: LoadBalancer
  
---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: redis
#  labels:
#    app: redis
#spec:
#  replicas: 1
#  template:
#    metadata:
#      name: redis
#      labels:
#        app: redis
#    spec:
#      containers:
#        - name: redis
#          image: redis
#          imagePullPolicy: IfNotPresent
#      restartPolicy: Always
#  selector:
#    matchLabels:
#      app: redis
#
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: redis
#spec:
#  selector:
#    app: redis
#  ports:
#    - port: 8080
#  type: ClusterIP
